//------------------------------------------------------------------------------
// <auto-generated>
//     This Name was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the Name is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Countries.Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class xmlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal xmlFiles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Countries.Tests.xmlFiles", typeof(xmlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;Countries xmlns:bk=&quot;urn:samples&quot;&gt;
        /// &lt;Country&gt;
        ///	&lt;Id&gt;1&lt;/Id&gt;
        ///    &lt;Name&gt;Poland&lt;/Name&gt;
        ///    &lt;Capital&gt;Warsaw&lt;/Capital&gt;
        ///    &lt;Currency&gt;PLN&lt;/Currency&gt;
        /// &lt;/Country&gt;
        /// &lt;Country&gt;
        ///	&lt;Id&gt;2&lt;/Id&gt;
        ///    &lt;Name&gt;England&lt;/Name&gt;
        ///    &lt;Capital&gt;London&lt;/Capital&gt;
        ///    &lt;Currency&gt;GBP&lt;/Currency&gt;
        /// &lt;/Country&gt;
        /// &lt;Country&gt;
        ///	&lt;Id&gt;3&lt;/Id&gt;
        ///    &lt;Name&gt;Germany&lt;/Name&gt;
        ///    &lt;Capital&gt;Berlin&lt;/Capital&gt;
        ///    &lt;Currency&gt;EUR&lt;/Currency&gt;
        /// &lt;/Country&gt;
        /// &lt;Country&gt;
        ///	&lt;Id&gt;4&lt;/Id&gt;
        ///    &lt;Name&gt;Spain&lt;/Name&gt;
        ///    &lt;Capital&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ListOfCountries {
            get {
                return ResourceManager.GetString("ListOfCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;settings xmlns:bk=&quot;urn:samples&quot;&gt;   
        ///&lt;calculator display=&quot;1&quot; /&gt; 
        /// &lt;details display=&quot;1&quot; /&gt; 
        ///   &lt;charge display=&quot;1&quot; /&gt; 
        ///   &lt;features&gt; 
        ///     &lt;feature Name=&quot;HAZ&quot; Value=&quot;CARGO&quot; /&gt; 
        ///     &lt;feature Name=&quot;IDL&quot; Value=&quot;DELIVERY&quot; /&gt; 
        ///    &lt;feature Name=&quot;LFT&quot; Value=&quot;TRUCK&quot; /&gt; 
        ///     &lt;feature Name=&quot;NFY&quot; Value=&quot;CARRIER CHARGE&quot; /&gt;
        ///  &lt;/features&gt; 
        ///&lt;/settings&gt;.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
    }
}
